apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev  

commonLabels:
  myenv: sitefrontendapp
commonAnnotations:
  apponwer: poc_team 

resources:
 - ns.yaml
 - ../../../apps/base/

patchesStrategicMerge:
- deployment_app.yaml
- replica-and-rollout-strategy.yaml

images:
- name: iamraj007/site
  newTag: v2

nameSuffix: -devenv
namePrefix: mysite-


