apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-frontend
  namespace: dev
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
