apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: siteargo-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: sitealias=iamraj007/site
    argocd-image-updater.argoproj.io/git-branch: main                         
    argocd-image-updater.argoproj.io/sitealias.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/sitealias.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/iamraj007/argo_apps.git
    targetRevision: HEAD
    path: siteapp/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
