apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mygitops-app-main
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=docker.io/iamraj007/gitopsapp  #repository name
    argocd-image-updater.argoproj.io/git-branch: main                                   #git branch 
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/iamraj007/argo_apps.git
    targetRevision: HEAD
    path: apps/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
