apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-frontend
spec:
  template:
    spec:
      containers:
        - name: gitops-front-container 
#          env:
#            - name: ENV_VAR
#              value: ENV_VAR_VALUE
