apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev  

commonLabels:
  myenv: devfrontendapp
commonAnnotations:
  apponwer: poc_guy 

resources:
 - ns.yaml
 - ../../../apps/base/

patchesStrategicMerge:
- deployment_app.yaml
- replica-and-rollout-strategy.yaml

images:
- name:  planethomeregistry.azurecr.io/terraformer
  newTag: 0.13.4_2

nameSuffix: -dev

