apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev  

commonLabels:
  myenv: devfrontend
commonAnnotations:
  apponwer: poc_guy 

resources:
 - ns.yaml
 - ../../../apps/base/

patchesStrategicMerge:
- deployment_app.yaml
- replica-and-rollout-strategy.yaml

images:
- name: iamraj007/gitopsapp
  newTag: 2a3390e7

nameSuffix: -dev

