apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev  

commonLabels:
  myenv: devfrontendapp
commonAnnotations:
  apponwer: poc_guy 

resources:
 - ns.yaml
 - ../../../apps/base/

patchesStrategicMerge:
- deployment_app.yaml
- replica-and-rollout-strategy.yaml

images:
- name: iamraj007/gitopsapp
  newTag: c0f49073

nameSuffix: -dev

