apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-nginx
  template:
    metadata:
      labels:
        app: gitops-nginx
    spec:
      containers:
      - image: iamraj007/gitopsapp:c8fac058 
        name: gitops-front-container
        ports:
        - containerPort: 80
          protocol: TCP
