apiVersion: v1
kind: Service
metadata:
  labels:
    app: site-nginx
  name: site-svc
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 5000
  selector:
    app: site-nginx
